version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: flash_sale_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: flash-sale-app
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_URL: jdbc:mysql://mysqldb:3306/flash_sale_db
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}

      # Cloud Redis (Variables will be picked from .env)
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      # Cloud Kafka (Variables will be picked from .env)
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}

      # Security & Mail
      JWT_SECRET: ${JWT_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

volumes:
  mysql_data: