spring.application.name=flash-sale-service

# MySQL Connection
spring.datasource.name=xxxxxxxxxxxx
spring.datasource.url=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
spring.datasource.username=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
spring.datasource.password=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT Configuration
# Generate a 256-bit secret key (32 characters long)
jwt.secret=ccccccccccccccccccccccccccccccccccccccc
jwt.expiration=86400000
